In [1]:
import autograd.numpy as np
from autograd import grad

In [2]:
def tanh(x):
    y= np.exp(-2.0 * x)
    return (1.0 -y)/ (1.0+y)


In [3]:
grad_tanh = grad(tanh)

In [5]:
(tanh(1.0001) - tanh(0.9999)) / 0.0002 

0.41997434264973155

In [8]:

def taylor_sine(x):  # Taylor approximation to sine function
    ans = currterm = x
    i = 0
    while np.abs(currterm) > 0.001:
        currterm = -currterm * x**2 / ((2 * i + 3) * (2 * i + 2))
        ans = ans + currterm
        i += 1
    return ans

grad_sine = grad(taylor_sine)
print ("Gradient of sin(pi) is", grad_sine(np.pi))

Gradient of sin(pi) is -0.9998995297042174


In [13]:
def sigmoid(x):
    return 0.5*(np.tanh(x) + 1)

def logistic_predictions(weights, inputs):
    # Outputs probability of a label being true according to logistic model.
    return sigmoid(np.dot(inputs, weights))

def training_loss(weights):
    # Training loss is the negative log-likelihood of the training labels.
    preds = logistic_predictions(weights, inputs)
    label_probabilities = preds * targets + (1 - preds) * (1 - targets)
    return -np.sum(np.log(label_probabilities))

# Build a toy dataset.
inputs = np.array([[0.52, 1.12,  0.77],
                   [0.88, -1.08, 0.15],
                   [0.52, 0.06, -1.30],
                   [0.74, -2.49, 1.39]])
targets = np.array([True, True, False, True])

# Define a function that returns gradients of training loss using Autograd.
training_gradient_fun = grad(training_loss)

# Optimize weights using gradient descent.
weights = np.array([0.0, 0.0, 0.0])
print ("Initial loss:", training_loss(weights))
for i in range(100):
    weights -= training_gradient_fun(weights) * 0.01
    print (weights)

print  ("Trained loss:", training_loss(weights))


Initial loss: 2.77258872224
[ 0.0162 -0.0251  0.0361]
[ 0.03123665 -0.04667378  0.06982363]
[ 0.04525273 -0.06519533  0.1014257 ]
[ 0.05838478 -0.08111776  0.13115308]
[ 0.07075467 -0.09484516  0.15922866]
[ 0.08246692 -0.10672405  0.18584608]
[ 0.09360939 -0.11704535  0.21117034]
[ 0.10425517 -0.12605073  0.23534081]
[ 0.11446488 -0.13394022  0.25847509]
[ 0.12428885 -0.14087938  0.28067268]
[ 0.13376903 -0.14700563  0.30201819]
[ 0.14294053 -0.15243342  0.32258406]
[ 0.15183296 -0.15725856  0.34243272]
[ 0.16047143 -0.16156162  0.36161842]
[ 0.16887736 -0.1654107   0.38018859]
[ 0.17706917 -0.16886365  0.39818503]
[ 0.18506278 -0.17196982  0.41564483]
[ 0.19287208 -0.1747715   0.43260106]
[ 0.20050921 -0.17730513  0.44908341]
[ 0.20798488 -0.17960216  0.46511869]
[ 0.2153086  -0.18168989  0.48073122]
[ 0.22248883 -0.18359207  0.49594313]
[ 0.22953315 -0.18532944  0.5107747 ]
[ 0.2364484  -0.18692015  0.52524454]
[ 0.24324075 -0.18838017  0.53936981]
[ 0.24991583 -0.18972352  0.553166