In [ ]:
from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
import icu as icu
import pandas as pd
import numpy as np

num_patients = 10
DEF_EPISODES = 10


In [ ]:
def f(x):
    global num_patients
    num_patients = x
    
interact(f,x=widgets.IntSlider(min=10,max=100000,step=100,value=10))

In [ ]:
patients = icu.icusim(num_patients)

In [ ]:
patients.indexes

In [ ]:
patients.df

In [ ]:
len(patients.columns)

In [ ]:
df = pd.DataFrame(np.random.randn(1,len(patients.columns)),index=patients.indexes, columns=patients.columns)

In [ ]:
df


In [ ]:
df2 = pd.DataFrame(np.random.randn(num_patients,len(patients.columns)), columns=patients.columns)

In [ ]:
df2.index.names = patients.indexes


In [ ]:
df2


In [ ]:
df3 =  pd.DataFrame(columns=patients.columns)

In [ ]:
x = df3['bloc'].max()
x += 1

In [ ]:
x == np.nan

In [ ]:
x

In [ ]:
np.isnan(x)

In [ ]:
np.random.randint(2,20)

In [ ]:
arr = []

In [ ]:
arr.append([1,2,3])

In [ ]:
bloc = 1
custid =2

In [ ]:
arr.append([bloc,custid,np.random.randn(1,len(patients.columns)-2)])

In [ ]:
values = np.random.randn(1,len(patients.columns)-2)
values = np.insert(values, 0, bloc,axis=1)
values = np.insert(values, 1, custid, axis=1)

In [ ]:
len(values[0])

In [ ]:
v = np.array([bloc,custid])
v = np.append(v,np.random.randn(1,len(patients.columns)-2))

In [ ]:
v

In [ ]:
len(v)

In [ ]:
df3.loc[custid*100+bloc] = v

In [ ]:
df3

In [ ]:
n = 16
gender = np.random.choice([0,1])
values = {'bloc':list(range(n)), 'custid':[custid]*n, 'gender':[gender]*n}

In [ ]:
values

In [ ]:
from_dict = pd.DataFrame(values)
df4 = pd.concat([df3, from_dict]) #default axis = 0


In [ ]:
df4['SOFA']

In [ ]:
values['SOFA'] = [12] * n
values['charttime'] = list(range(4570416000,4570416000 + (n *14400), 14400))


In [ ]:
values

In [ ]:
def is_permutation(n,L):
    if len(L) != n:
        return False
    if len(set(L)) != n:
        return False
    for i in range(1,n+1):
        if not i in L:
            return False
    return True



print (is_permutation(4,[1,2,3,4]), "t")
print (is_permutation(4,[2,3,1,4]), "t")
print (is_permutation(4,[1,2,3,4,5]), "f")
print (is_permutation(4,[1,2,2,3,4]), "f")
print (is_permutation(4,[2,2,3,4]), "f")

In [21]:
import sys
sys.path.append('../utils')
sys.path.append('../DQN')

import PatientRecordProcessor as pr
import DQN as dqn
import numpy as np
import tensorflow as tf
import pandas as pd

    

In [2]:
prefix = '../../data/'
prp = pr.PatientRecordProcessor(prefix + 'Sepsis_imp.csv', prefix + 'states_list.pkl')


loading dataset ...
loading clustered states ...
discretizing actions ...
initialization succeed


In [5]:
histories = prp.build_training_history()

In [8]:
tf.reset_default_graph()

In [12]:
MEMORY_SIZE = 1280
ACTION_SPACE = 25
FEATURES = 51
NUM_EPOCHES = 100

## speicify output_path while tunning parameters
with tf.variable_scope('dueling'):
    dueling_DQN = dqn.DQN(
        num_actions=ACTION_SPACE, num_features=FEATURES, mem_size=MEMORY_SIZE,
        dueling=True, output_graph=True)

In [23]:
data = np.genfromtxt('../../data/Sepsis_imp.csv', dtype=float, delimiter=',', skip_header=1)
        

In [24]:
data

array([[  1.00000000e+00,   3.00000000e+00,   7.24505280e+09, ...,
          0.00000000e+00,   0.00000000e+00,   1.00000000e+00],
       [  2.00000000e+00,   3.00000000e+00,   7.24506720e+09, ...,
          0.00000000e+00,   0.00000000e+00,   1.00000000e+00],
       [  3.00000000e+00,   3.00000000e+00,   7.24508160e+09, ...,
          0.00000000e+00,   0.00000000e+00,   1.00000000e+00],
       ..., 
       [  1.10000000e+01,   9.99950000e+04,   4.61291724e+09, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  1.20000000e+01,   9.99950000e+04,   4.61293164e+09, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  1.30000000e+01,   9.99950000e+04,   4.61294604e+09, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

In [44]:
df = pd.read_csv('../../data/Sepsis_imp.csv')

In [25]:
data2 = df.as_matrix()

In [26]:
data2


array([[  1.00000000e+00,   3.00000000e+00,   7.24505280e+09, ...,
          0.00000000e+00,   0.00000000e+00,   1.00000000e+00],
       [  2.00000000e+00,   3.00000000e+00,   7.24506720e+09, ...,
          0.00000000e+00,   0.00000000e+00,   1.00000000e+00],
       [  3.00000000e+00,   3.00000000e+00,   7.24508160e+09, ...,
          0.00000000e+00,   0.00000000e+00,   1.00000000e+00],
       ..., 
       [  1.10000000e+01,   9.99950000e+04,   4.61291724e+09, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  1.20000000e+01,   9.99950000e+04,   4.61293164e+09, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  1.30000000e+01,   9.99950000e+04,   4.61294604e+09, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

In [35]:
np.allclose(data,data2)

True

In [28]:
data.shape

(252204, 59)

In [29]:
data2.shape

(252204, 59)

In [33]:
data[252203]

array([  1.30000000e+01,   9.99950000e+04,   4.61294604e+09,
         0.00000000e+00,   8.53873934e+03,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   2.00000000e+00,
         7.96000000e+01,   1.50000000e+01,   7.56666667e+01,
         1.39333333e+02,   8.90000000e+01,   7.63333333e+01,
         5.43062201e-01,   2.00000000e+01,   9.73333333e+01,
         3.65555573e+01,   2.10000000e-01,   3.80000000e+00,
         1.42000000e+02,   1.04000000e+02,   8.50000000e+01,
         6.00000000e+00,   8.00000000e-01,   2.00000000e+00,
         9.30000019e+00,   1.12892857e+00,   2.70000000e+01,
         4.20000000e+01,   3.17857143e+01,   7.00000000e-01,
         4.00000000e+00,   1.49000000e+01,   1.33000000e+01,
         2.34000000e+02,   3.12000000e+01,   1.42000000e+01,
         1.29090909e+00,   7.39500000e+00,   1.10857143e+02,
         4.04000000e+01,   0.00000000e+00,   1.61111111e+00,
         2.70000000e+01,   5.27891156e+02,   0.00000000e+00,
         0.00000000e+00,

In [34]:
data2[252203]

array([  1.30000000e+01,   9.99950000e+04,   4.61294604e+09,
         0.00000000e+00,   8.53873934e+03,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   2.00000000e+00,
         7.96000000e+01,   1.50000000e+01,   7.56666667e+01,
         1.39333333e+02,   8.90000000e+01,   7.63333333e+01,
         5.43062201e-01,   2.00000000e+01,   9.73333333e+01,
         3.65555573e+01,   2.10000000e-01,   3.80000000e+00,
         1.42000000e+02,   1.04000000e+02,   8.50000000e+01,
         6.00000000e+00,   8.00000000e-01,   2.00000000e+00,
         9.30000019e+00,   1.12892857e+00,   2.70000000e+01,
         4.20000000e+01,   3.17857143e+01,   7.00000000e-01,
         4.00000000e+00,   1.49000000e+01,   1.33000000e+01,
         2.34000000e+02,   3.12000000e+01,   1.42000000e+01,
         1.29090909e+00,   7.39500000e+00,   1.10857143e+02,
         4.04000000e+01,   0.00000000e+00,   1.61111111e+00,
         2.70000000e+01,   5.27891156e+02,   0.00000000e+00,
         0.00000000e+00,

In [38]:
class Foo2(object):
    p = 2
    
    def retp(self):
        return self.p
    
x = Foo2()


In [39]:
x.retp()

2

In [62]:
z = 0
observ_cols = ['elixhauser','re_admission', 'SOFA', 'SIRS', 'Weight_kg', 'GCS', 'HR',
                'SysBP', 'MeanBP', 'DiaBP', 'Shock_Index', 'RR', 'SpO2',
                'Temp_C', 'FiO2_1', 'Potassium', 'Sodium', 'Chloride',
                'Glucose', 'BUN', 'Creatinine', 'Magnesium', 'Calcium',
                'Ionised_Ca', 'CO2_mEqL', 'SGOT', 'SGPT', 'Total_bili',
                'Albumin', 'Hb', 'WBC_count', 'Platelets_count', 'PTT',
                'PT', 'INR', 'Arterial_pH', 'paO2', 'paCO2',
                'Arterial_BE', 'Arterial_lactate', 'HCO3', 'PaO2_FiO2',
                'output_total', 'output_4hourly',
                'sedation', 'mechvent', 'rrt']
for i, row in df.iterrows():
    print (row[observ_cols].as_matrix())
    z += 1
    if (z > 10): break


[   0.            0.            9.            4.           77.5          15.
  122.14285714   95.14285714   64.42857143   58.            1.28378378
   30.42857143   96.42857143   39.23809354    1.            3.1         140.
  103.          110.           21.            0.9           1.2           7.5
    1.05         18.           49.           65.            3.5           2.8
   11.5          14.8         107.           32.9          22.9           2.3
    7.36         88.           34.           -5.            5.1          23.
   88.          230.          230.            0.            0.            0.        ]
[   0.            0.            8.            3.           77.5          15.
  113.18181818   91.54545455   66.45454545   59.81818182    1.23634558
   32.18181818   93.63636364   37.59596044    1.            3.1         140.
  103.          110.           21.            0.9           1.2           7.5
    1.05         18.           49.           65.            3.5           2

In [60]:
df.loc[:,'input_4hourly_tev']

0         2100.000
1         1999.000
2          105.000
3           60.000
4           60.000
5          533.000
6           10.000
7            0.000
8            0.000
9            0.000
10           0.000
11           0.000
12           0.000
13           0.000
14           0.000
15           0.000
16           0.000
17           0.000
18        1300.000
19         320.000
20         320.000
21         160.000
22           0.000
23           0.000
24          75.000
25         125.000
26         100.000
27          75.000
28           0.000
29        1031.000
            ...   
252174    3527.000
252175    2098.417
252176      68.000
252177      68.000
252178      35.000
252179      20.000
252180      20.000
252181      20.000
252182      20.000
252183      20.000
252184      21.667
252185      13.333
252186      20.000
252187      25.000
252188      20.000
252189      20.000
252190      20.000
252191       0.000
252192     230.250
252193     483.333
252194     720.000
252195     5

In [58]:
df.columns[3]

'gender'